CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;

CREATE TABLE IF NOT EXISTS records (
  time                 TIMESTAMP         PRIMARY KEY,
  orbit_number         SMALLINT          NOT NULL,
  sub_orbit_type       SMALLINT          NOT NULL,
  tm_station           VARCHAR(8)        NOT NULL,
  sft_version          SMALLINT          NOT NULL,
  sft_sub_version      SMALLINT          NOT NULL,
  cal_version          SMALLINT          NOT NULL,
  cal_sub_version      SMALLINT          NOT NULL,
  geoc_lat             REAL              NOT NULL,
  geoc_long            REAL              NOT NULL,
  altitude             REAL              NOT NULL,
  local_time           REAL              NOT NULL,
  geomag_lat           REAL              NOT NULL,
  geomag_long          REAL              NOT NULL,
  mlt                  REAL              NOT NULL,
  inv_lat              REAL              NOT NULL,
  mc_ilwain_l          REAL              NOT NULL,
  conjsat_geoc_lat     REAL              NOT NULL,
  conjsat_geoc_long    REAL              NOT NULL,
  nconj_110_geoc_lat   REAL              NOT NULL,
  nconj_110_geoc_long  REAL              NOT NULL,
  sconj_110_geoc_lat   REAL              NOT NULL,
  sconj_110_geoc_long  REAL              NOT NULL,
  component            REAL[3]           NOT NULL,
  gyrofreq             REAL              NOT NULL,
  solar_position       REAL[3]           NOT NULL,
  sft_version_1        SMALLINT          NOT NULL,
  sft_sub_version_1    SMALLINT          NOT NULL,
  aij                  REAL[9]           NOT NULL,
  bij                  REAL[9]           NOT NULL,
  quality              SMALLINT          NOT NULL,
  sft_version_2        SMALLINT          NOT NULL,
  sft_sub_version_2    SMALLINT          NOT NULL,
  data_type            VARCHAR(21)       NOT NULL,
  hk                   SMALLINT[32]      NOT NULL,
  coord_syst           VARCHAR(9)        NOT NULL,
  data_unit            VARCHAR(16)       NOT NULL,
  freq                 REAL              NOT NULL,
  ns                   SMALLINT          NOT NULL,
  t_dur                REAL              NOT NULL,
  nam1c                VARCHAR(3)        NOT NULL,
  wf1                  REAL[8192]        NOT NULL
);

SELECT create_hypertable('records', 'time', if_not_exists => TRUE, chunk_time_interval => interval '1 month');